name: PurpurPackUpdater
version: '1.0-SNAPSHOT'
main: org.purpurmc.purpurPackUpdater.PurpurPackUpdater
api-version: '1.21'
commands:
  checkup:
    permission: packupdater.checkup
    description: checks which packs need updates
  ppureload:
    permission: packupdater.reload
    description: reloads the config/locale
permissions:
  packupdater.checkup:
    default: op
    description: Allows the player to run the update check command
  packupdater.reload:
    default: op
    description: Allows reloading the config (locale)